[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
hilt = "2.57.2"
hilt-work = "1.3.0"
navigationCompose = "2.9.5"
appcompat = "1.7.1"
room_version = "2.8.3"
work-runtime = "2.11.0"
apache-commons = "3.20.0"
kotlin-serialization-json = "1.9.0"
firebaseBom = "33.1.0"
credentials = "1.2.2"
googleId = "1.1.0"
googleServices = "4.4.2"
coil = "2.7.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose =  { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose"}
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-work" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-work" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room_version" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room_version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room_version" }
android-work-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime"}
android-work = { module = "androidx.work:work-runtime", version.ref = "work-runtime"}
apache-commons = { module= "org.apache.commons:commons-lang3", version.ref = "apache-commons"}
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleId" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlin-kapt = { id = "kotlin-kapt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.21-1.0.27" }

